repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
                # run curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
                # run brew install pre-commit
    hooks:
      - id: terraform-fmt
      #- id: terraform-validate
      - id: tflint
        args:
          - "--config=.tflint.hcl"
      - id: shellcheck