name: "Terraform CI Pipeline"

on:
  pull_request:

env:
  TERRAFORM_VERSION: "1.9.6"

permissions:
  id-token: write
  contents: write # Ensure that the workflow has permission to write to PR comments
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        id: fmtmain
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          TF_IN_AUTOMATION: 1
        run: terraform plan

      - name: Submit PR Comment
        uses: actions/github-script@v7
        env:
          COMMENT_BODY: "${{ steps.plan.outputs.stdout }}"
          COMMENT_TITLE: "${{ github.workflow }}"
          COMMENT_AUTHOR: "${{ github.actor }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/js/terraform-comment.js');
            await script({github, context});